"""All available cards"""
from copy import deepcopy

from game.cards import card as cards

ALL_CARDS = []

ALL_CARDS.extend([
    cards.MinionCard(name="Abomination",
                     health=4,
                     attack=4,
                     cost=5),
    cards.MinionCard(name="Barnes",
                     health=4,
                     attack=3,
                     cost=4),
    cards.MinionCard(name="Batterhead",
                     health=12,
                     attack=3,
                     cost=8),
    cards.MinionCard(name="Bearshark",
                     health=3,
                     attack=4,
                     cost=3),
    cards.MinionCard(name="Cenarius",
                     health=8,
                     attack=5,
                     cost=9),
    cards.MinionCard(name="Enchanted Raven",
                     health=2,
                     attack=2,
                     cost=1),
    cards.MinionCard(name="Spider Tank",
                     health=4,
                     attack=3,
                     cost=3),
    cards.MinionCard(name="Ice Rager",
                     health=2,
                     attack=5,
                     cost=3),
    cards.MinionCard(name="Worgen Greaser",
                     health=3,
                     attack=6,
                     cost=4),
    cards.MinionCard(name="Am'gam Rager",
                     health=5,
                     attack=1,
                     cost=3),
    cards.MinionCard(name="Boom Reaver",
                     health=9,
                     attack=7,
                     cost=10),
    cards.MinionCard(name="Darius Crowley",
                     health=4,
                     attack=4,
                     cost=5),
    cards.MinionCard(name="Iron Juggernaut",
                     health=5,
                     attack=6,
                     cost=6),
    cards.MinionCard(name="King Mosh",
                     health=7,
                     attack=9,
                     cost=9),
    cards.MinionCard(name="Lord Of The Arena",
                     health=5,
                     attack=6,
                     cost=6),
    cards.MinionCard(name="Massive Gnoll",
                     health=3,
                     attack=5,
                     cost=4),
    cards.MinionCard(name="Orc Warrior",
                     health=2,
                     attack=3,
                     cost=2),
    cards.MinionCard(name="River Crocolisk",
                     health=3,
                     attack=2,
                     cost=2),
    cards.MinionCard(name="Tabbycat",
                     health=1,
                     attack=1,
                     cost=1),
    cards.MinionCard(name="Treant",
                     health=2,
                     attack=2,
                     cost=2),
])


def get_all_available_cards():
    return list(map(lambda x: deepcopy(x), ALL_CARDS))
